buildscript {
    repositories {
        mavenCentral()
        maven {
            name = "forge"
            url = "https://maven.minecraftforge.net/"
        }
    }
    dependencies {
        classpath ('com.anatawa12.forge:ForgeGradle:1.2-1.1.+') {
            changing = true
        }
    }
}

plugins {
    id 'java-library'
    id 'maven-publish'
}

apply plugin: 'forge'

// These settings allow you to choose what version of Java you want to be compatible with. Forge 1.7.10 runs on Java 6 to 8.
sourceCompatibility = 8
targetCompatibility = 8

version = project.version
group = project.group

minecraft {
    version = project.minecraft_version + "-" + project.forge_version
    runDir = "run"
}

def geckoLibJarName = "geckolib-unofficial-1.7.10-1.0.4.jar"
def geckoLibJar = file("libs/$geckoLibJarName")
def deobfGeckoLibJar = file("$buildDir/deobf-libs/${geckoLibJarName.replace('.jar', '-dev.jar')}")
def geckoLibSrgMcp = file("$buildDir/deobf-libs/geckolib-srg-mcp.srg")
def forgeGradleDelayed = { String path ->
    new net.minecraftforge.gradle.delayed.DelayedFile(project, path, minecraft.plugin)
}

configurations.implementation.dependencies.removeAll { dependency ->
    dependency instanceof org.gradle.api.artifacts.SelfResolvingDependency
            && dependency.resolve().any { file -> file.canonicalFile == geckoLibJar.canonicalFile }
}

task patchGeckoLibSrgMcp {
    dependsOn "genSrgs"
    inputs.file forgeGradleDelayed(net.minecraftforge.gradle.user.UserConstants.DEOBF_SRG_MCP_SRG)
    outputs.file geckoLibSrgMcp
    doLast {
        def baseSrg = forgeGradleDelayed(net.minecraftforge.gradle.user.UserConstants.DEOBF_SRG_MCP_SRG).call()
        geckoLibSrgMcp.parentFile.mkdirs()
        geckoLibSrgMcp.text = baseSrg.text
        geckoLibSrgMcp << "\n"
        geckoLibSrgMcp << "MD: cpw/mods/fml/common/registry/FMLControlledNamespacedRegistry/func_82594_a (Ljava/lang/String;)Ljava/lang/Object; cpw/mods/fml/common/registry/FMLControlledNamespacedRegistry/getObject (Ljava/lang/String;)Ljava/lang/Object;\n"
        geckoLibSrgMcp << "MD: cpw/mods/fml/common/registry/FMLControlledNamespacedRegistry/func_148754_a (I)Ljava/lang/Object; cpw/mods/fml/common/registry/FMLControlledNamespacedRegistry/getObjectById (I)Ljava/lang/Object;\n"
    }
}

task deobfGeckoLib(type: net.minecraftforge.gradle.tasks.ProcessJarTask) {
    dependsOn "downloadMcpTools", patchGeckoLibSrgMcp
    setInJar(forgeGradleDelayed("libs/$geckoLibJarName"))
    setOutCleanJar(forgeGradleDelayed("{BUILD_DIR}/deobf-libs/${geckoLibJarName.replace('.jar', '-dev.jar')}"))
    setOutDirtyJar(forgeGradleDelayed("{BUILD_DIR}/deobf-libs/${geckoLibJarName.replace('.jar', '-dev.jar')}"))
    setSrg(new net.minecraftforge.gradle.delayed.DelayedFile(geckoLibSrgMcp))
    setExceptorJson(forgeGradleDelayed(net.minecraftforge.gradle.user.UserConstants.EXC_JSON))
    setExceptorCfg(forgeGradleDelayed(net.minecraftforge.gradle.user.UserConstants.EXC_MCP))
    setFieldCsv(forgeGradleDelayed(net.minecraftforge.gradle.user.UserConstants.FIELD_CSV))
    setMethodCsv(forgeGradleDelayed(net.minecraftforge.gradle.user.UserConstants.METHOD_CSV))
    setApplyMarkers(false)
    setStripSynthetics(false)
    doFirst {
        deobfGeckoLibJar.parentFile.mkdirs()
    }
}

repositories {
    // Adds the 'libs' folder in the project directory as a flat directory
    flatDir {
        dir 'libs'
    }
}
dependencies {
    implementation 'lotr.common.LOTRMod:LOTRMod:36.15'
    implementation fileTree(dir: 'libs', exclude: geckoLibJarName)
    implementation files(deobfGeckoLibJar) {
        builtBy deobfGeckoLib
    }

    // you may put jars on which you depend on in ./libs
    // or you may define them like so..
    //compile "some.group:artifact:version:classifier"
    //compile "some.group:artifact:version"

    // real examples
    //compile 'com.mod-buildcraft:buildcraft:6.0.8:dev'  // adds buildcraft to the dev env
    //compile 'com.googlecode.efficient-java-matrix-library:ejml:0.24' // adds ejml to the dev env

    // for more info...
    // http://www.gradle.org/docs/current/userguide/artifact_dependencies_tutorial.html
    // http://www.gradle.org/docs/current/userguide/dependency_management.html
}

processResources {
    // This will ensure that this task is redone when the versions change.
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    // Replace values in only mcmod.info.
    filesMatching('mcmod.info') {
        // Replace version and mcversion.
        expand 'version':project.version, 'mcversion':project.minecraft.version
    }
}

// Ensures that the encoding of source files is set to UTF-8, see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}

// This task creates a .jar file containing the source code of this mod.
task sourcesJar(type: Jar, dependsOn: classes) {
    classifier = "sources"
    from sourceSets.main.allSource
}

// This task creates a .jar file containing a deobfuscated version of this mod, for other developers to use in a development environment.
task devJar(type: Jar) {
    classifier = "dev"
    from sourceSets.main.output
}

runClient {
    jvmArgs = [
            "-Xmx2G",
            // you usually dont need backups in dev environment
            "-Dfml.doNotBackup=true",
            // intel gpu performance
            "-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump",
            // default gc settings for minecraft
            "-XX:+UnlockExperimentalVMOptions",
            "-XX:+UseG1GC",
            "-XX:G1NewSizePercent=20",
            "-XX:G1ReservePercent=20",
            "-XX:MaxGCPauseMillis=50",
            "-XX:G1HeapRegionSize=32M"
    ]
}

// Creates the listed artifacts on building the mod.
artifacts {
    archives sourcesJar
    archives devJar
}

// This block configures any maven publications you want to make.
publishing {
    publications {
        mavenJava(MavenPublication) {
        // Add any other artifacts here that you would like to publish!
            artifact(jar) {
                builtBy build
            }
            artifact(sourcesJar) {
                builtBy sourcesJar
            }
            artifact(devJar) {
                builtBy devJar
            }
        }
    }
    // This block selects the repositories you want to publish to.
    repositories {
        // Add the repositories you want to publish to here.
    }
}
